version: '3'

networks:
  app:
    driver: bridge
services:
  mysqldb:
    networks:
      - app
    image: mysql:5.7
    restart: always
    container_name: mysqldb
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
  server:
    networks:
      - app
    build:
      context: .
    container_name: server
    ports:
      - '8080:8080'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysqldb
